name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27

    - name: Install direnv
      uses: aldoborrero/direnv-nix-action@v2
      with:
        use_nix_profile: true
        nix_channel: nixpkgs

    - name: Check formatting
      run: find . -name '*.hs' ! -path '*dist-newstyle*' | xargs ormolu --color always --check-idempotence --mode check

    - name: Cabal (build)
      run: cabal build

    - name: Cabal (run)
      run: cabal run

    - name: Cabal (test)
      run: cabal test

    - name: Nix (build)
      run: nix build

    - name: Nix (run)
      run: nix run

    - uses: actions/checkout@v4
